var domains = ["Vaobo88.com",
               "Caoviet.net", 
               "Lodeonline.top", 
               "Bet4vn.top", 
               "Danhbaifi88.com", 
               "Doithuonguytin.com", 
               "Casinoonline.vc", 
               "Songbac.top", 
               "Bongso88.com",
               "Gbpnews.com", 
               "Nhacaiuytin.vc",
               "adfp-sd.com",
               "fwbsaigon.club",
               "nhacaiuytin168.com"].sort();
